services:
  frontend:
    container_name: waygame
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BLOCK_ID: ${NEXT_PUBLIC_BLOCK_ID}
        NEXT_PUBLIC_BLOCK_ID_INIT: ${NEXT_PUBLIC_BLOCK_ID_INIT}
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
    restart: always
    networks:
      - dev

  backend:
    container_name: express
    build: ./backend
    restart: always
    volumes:
      - ./backend/stats.json:/app/stats.json

    env_file: 
      - ./.env
    depends_on: 
      - db
      - redis  
      

    networks:
      - dev

  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # ports: 
    #   - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine # используем стабильный легковесный Nginx образ
    container_name: nginx # имя контейнера на хосте, удобно для docker logs/exec
    ports:
      - "80:80" # проброс порта HTTP наружу
      - "443:443" # проброс порта HTTPS наружу
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - "./gzip.conf:/etc/nginx/gzip.conf:ro" # монтируем gzip файл внутрь контейнера
    restart: always # автоматически перезапускать контейнер при падении
    depends_on:
      - frontend # запускать nginx после frontend 
      - backend
    networks:
      - dev # подключаем контейнер к сети dev
  redis:
    container_name: redis_data
    image: redis:7
    restart: unless-stopped
    # ports:
    #   - 6380:6379
    command: >
      sh -c '
       mkdir -p /usr/local/etc/redis &&
       echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
       echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
       echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
       echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
       echo "dir /data" >> /usr/local/etc/redis/redis.conf &&
       redis-server /usr/local/etc/redis/redis.conf
      '
    volumes:
      - redis_data:/data

    env_file:
      - ./.env

    networks:
      - dev

volumes:
  postgres_data:   
  redis_data:   
networks:
  dev:
