export const TYPES = {
  Application: Symbol.for("App"),
  LoggerService: Symbol.for("LoggerService"),
  DotenvConfig: Symbol.for("DotenvConfig"),
  BotCommands: Symbol.for("BotCommands"),
  AddCommands: Symbol.for("BotCommands"),
  OnMessageCommand: Symbol.for("OnMessageCommand"),
  ExceptionFilter: Symbol.for("ExceptionFilter"),
  AdsController: Symbol.for("AdsController"),
  AdsService: Symbol.for("AdsService"),
  AdsRepository: Symbol.for("AdsRepository"),
  Models: Symbol.for("Models"),
  SequelizeService: Symbol.for("SequelizeService"),
  UserController: Symbol.for("UserController"),
  UserRepository: Symbol.for("UserRepository"),
  UserService: Symbol.for("UserService"),
  TicketController: Symbol.for("TicketController"),
  TicketService: Symbol.for("TicketService"),
  TicketRepository: Symbol.for("TicketRepository"),
  SessionService: Symbol.for("SessionService"),
  RedisConfig: Symbol.for("RedisConfig"),
  SessionConfig: Symbol.for("SessionConfig"),
  AuthController: Symbol.for("AuthController"),
  AuthService: Symbol.for("AuthService"),
  WinnerController: Symbol.for("WinnerController"),
  WinnerService: Symbol.for("WinnerService"),
  WinnerRepository: Symbol.for("WinnerRepository"),
};
